name: CI

on:
  pull_request:
    branches: [ master ]
  issue_comment:
  pull_request_target:
    branches: [ master]
env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  COMMENT_STRING: ${{ github.event.comment.body }}
  EVENT_TYPE: ${{ github.event.action }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Display the path
        run: |
          echo "Event type: ${{env.EVENT_TYPE}}"
          echo "Event Name: ${{env.GITHUB_EVENT_NAME}}"
          if [[ "$COMMENT_STRING" == *"screenshot:"* ]];
          then
            echo "Started generating screenshots.."
          else
            echo "Started fetching test plans..."
          fi
        shell: bash
      - name: Print PR Number
        run: |
          echo PRNumber1
          echo 1 ${{ github.event.issue.number }}
          echo PR Number3: ${{github.event.pull_request.number}}
          echo "PR number4 = ${{ env.PR_NUMBER }}"
          echo "PR number5 = ${{ github.event.pull_request.number }}"
          echo "Comment ${{env.COMMENT_STRING}}"
          echo "event type1: ${{env.GITHUB_EVENT_NAME}}"
#       - name: upload to S3
#         uses: RandhirMSingh/S3Manager@main
#         with:
#           args: --acl public-read
#         env:
#           FILE:  "."
#           AWS_REGION: 'ap-south-1'
#           S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#           S3_KEY: ${{ secrets.S3_KEY }}
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           REPO: ${{ github.repository }}
#           PR_NUMBER: ${{ github.event.issue.number }}
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
